// Reads sdk/.env and writes sdk/env.local.js — a plain <script> the demo
// page loads to get HAVISIQ_API_KEY onto `window`, since example.html is
// opened as a bare static file (no bundler, no server) and can't read a
// .env file directly. Re-run this (`npm run gen-env`) after changing the
// key in .env. Both .env and env.local.js are gitignored — this script
// is the only place the real key value passes through.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const sdkDir = dirname(dirname(fileURLToPath(import.meta.url)));
const envPath = join(sdkDir, '.env');
const outPath = join(sdkDir, 'env.local.js');

let text;
try {
  text = readFileSync(envPath, 'utf8');
} catch {
  console.error(`gen-env: no .env file at ${envPath} — copy .env.example to .env and fill in HAVISIQ_API_KEY first.`);
  process.exit(1);
}

const match = text.match(/^HAVISIQ_API_KEY=(.*)$/m);
if (!match || !match[1].trim()) {
  console.error('gen-env: HAVISIQ_API_KEY is not set in sdk/.env');
  process.exit(1);
}
const apiKey = match[1].trim();

writeFileSync(
  outPath,
  `// Generated by scripts/gen-env.mjs from .env — do not edit directly, do not commit.\nwindow.HAVISIQ_API_KEY = ${JSON.stringify(apiKey)};\n`,
);
console.log(`gen-env: wrote ${outPath}`);
